const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../JonsboCanvas/NeteaseCdpBridge.cs'), 'utf8');
const start = source.indexOf('string script = @"') + 'string script = @"'.length;
const end = source.indexOf('})()";', start) + 4;
const template = source.slice(start, end);
const script = binding => template.replace('" + bindingLiteral + @"', JSON.stringify(binding));
const events = new Map();
const received = [];
let nativeRegistrations = 0;
const sdk = { call() {}, rxFromNativeEvent(name) { return { subscribe(callback) {
    events.set(name, callback);
    return { unsubscribe() { events.delete(name); } };
} }; } };
const req = Object.assign(() => {}, { c: { arbitraryModuleNumber: { exports: { playerEvents: sdk } } } });
const context = vm.createContext({ received, nativeRegistrations: 0 });
vm.runInContext('window=globalThis; channel={registerCall(){nativeRegistrations++}}; channel.registerCall.__HACKED__=true; webpackJsonp=[]; firstBinding=p=>received.push(["first",JSON.parse(p)]); secondBinding=p=>received.push(["second",JSON.parse(p)]);', context);
context.__myCanvasWebpackRequire = req;
assert.equal(vm.runInContext(script('firstBinding'), context), 'jonsbo-installed-v8-sdk');
assert.equal(events.size, 4);
assert.equal(context.nativeRegistrations, 0);
events.get('audioplayer.onPlayProgress')(['123_RANDOM', 10, 1]);
assert.equal(received[0][0], 'first');
assert.equal(received[0][1].eventName, 'progress');
assert.equal(vm.runInContext(script('secondBinding'), context), 'jonsbo-installed-v8-sdk');
assert.equal(events.size, 4);
events.get('audioplayer.onPlayProgress')(['123_RANDOM', 11, 1]);
assert.equal(received[1][0], 'second');
const unavailable = vm.createContext({});
vm.runInContext('window=globalThis;channel={registerCall(){throw Error("must not replace player handlers")}};channel.registerCall.__HACKED__=true;', unavailable);
assert.equal(vm.runInContext(script('binding'), unavailable), 'sdk-unavailable');
const legacy = vm.createContext({});
vm.runInContext('window=globalThis;registered=[];channel={registerCall(name,callback){registered.push(name)}};', legacy);
assert.equal(vm.runInContext(script('binding'), legacy), 'jonsbo-installed-v8-legacy');
assert.equal(legacy.registered.length, 4);
console.log('PASS shared SDK discovery, native-handler preservation, event forwarding, reconnect reuse, safe incompatibility, legacy hooks');
